### ISSUE TITLE
Upload causes crash

### ISSUE THREAD

**Issue by loudmouth** [contentful/contentful-management.rb#124]
Rvm: 2.4.1
contentful-management: 1.8.1

My script:

```
#!/usr/bin/ruby

require 'contentful/management'

access_token = ENV['PERSONAL_CMA_TOKEN']
client = Contentful::Management::Client.new(access_token)

my_space = client.spaces.find(ENV['MY_SPACE_ID'])
space_id = my_space.id

## Upload
upload = client.uploads.create(space_id, './test-image.png')
```

causes the following output:

```
/Users/jpwright/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/openssl/buffering.rb:325:in `syswrite': Broken pipe (Errno::EPIPE)
	from /Users/jpwright/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/openssl/buffering.rb:325:in `do_write'
	from /Users/jpwright/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/openssl/buffering.rb:343:in `write'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/http-2.2.2/lib/http/timeout/null.rb:51:in `write'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/http-2.2.2/lib/http/request/writer.rb:99:in `write'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/http-2.2.2/lib/http/request/writer.rb:82:in `send_request'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/http-2.2.2/lib/http/request/writer.rb:42:in `stream'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/http-2.2.2/lib/http/request.rb:113:in `stream'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/http-2.2.2/lib/http/connection.rb:74:in `send_request'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/http-2.2.2/lib/http/client.rb:63:in `perform'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/http-2.2.2/lib/http/client.rb:41:in `request'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/http-2.2.2/lib/http/chainable.rb:26:in `post'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/contentful-management-1.8.1/lib/contentful/management/http_client.rb:85:in `public_send'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/contentful-management-1.8.1/lib/contentful/management/http_client.rb:85:in `http_send'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/contentful-management-1.8.1/lib/contentful/management/http_client.rb:30:in `post_http'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/contentful-management-1.8.1/lib/contentful/management/client.rb:315:in `block in post'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/contentful-management-1.8.1/lib/contentful/management/client.rb:252:in `execute_request'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/contentful-management-1.8.1/lib/contentful/management/client.rb:314:in `post'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/contentful-management-1.8.1/lib/contentful/management/request.rb:47:in `post'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/contentful-management-1.8.1/lib/contentful/management/resource_requester.rb:31:in `create'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/contentful-management-1.8.1/lib/contentful/management/resource.rb:209:in `create'
	from /Users/jpwright/.rvm/gems/ruby-2.4.1/gems/contentful-management-1.8.1/lib/contentful/management/client_association_methods_factory.rb:37:in `create'
	from test-upload.rb:17:in `<main>'
```

What might the issue be?

Additionally, I've noticed that acceptance tests in `spec/lib/contentful/management/` only test that the returned object is of type `Contentful::Management::Upload` but does not test that any of the relevant properties have correct value

**Comment by loudmouth** [comment]
I have also tried the same thing by assigning path explicitly and using the following:

```
path = ::File.join('/Users', 'me', 'Contentful', 'ruby', 'upload-test', 'test-image.png')
::File.open(path, 'rb') do |f|
  upload = client.uploads.create(space_id, f)
end

```
