### ISSUE TITLE
Gem is not thread safe

### ISSUE THREAD

**Issue by Soliah** [contentful/contentful-management.rb#144]
Doesn't look like this gem is thread safe. Using https://github.com/grosser/parallel with `in_threads` I get the following errors when iterating over entries:

```
/Users/cchow/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/contentful-management-1.10.0/lib/contentful/management/request.rb:13:in `initialize': undefined method `version=' for nil:NilClass (NoMethodError)
        from /Users/cchow/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/contentful-management-1.10.0/lib/contentful/management/resource_requester.rb:84:in `new'
        from /Users/cchow/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/contentful-management-1.10.0/lib/contentful/management/resource_requester.rb:84:in `delete'
        from /Users/cchow/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/contentful-management-1.10.0/lib/contentful/management/resource_requester.rb:51:in `unarchive'
        from /Users/cchow/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/contentful-management-1.10.0/lib/contentful/management/resource/publisher.rb:21:in `unpublish'
        from entry.rb:38:in `block (3 levels) in <main>'
        from /Users/cchow/.rbenv/versions/2.3.4/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
        from entry.rb:37:in `block (2 levels) in <main>'
        from /Users/cchow/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/parallel-1.12.1/lib/parallel.rb:486:in `call_with_index'
        from /Users/cchow/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/parallel-1.12.1/lib/parallel.rb:342:in `block (2 levels) in work_in_threads'
        from /Users/cchow/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/parallel-1.12.1/lib/parallel.rb:495:in `with_instrumentation'
        from /Users/cchow/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/parallel-1.12.1/lib/parallel.rb:341:in `block in work_in_threads'
        from /Users/cchow/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/parallel-1.12.1/lib/parallel.rb:206:in `block (2 levels) in in_threads'
```

The script I was running:

```ruby
require 'benchmark'
require 'optparse'
require 'parallel'
require 'contentful/management'
require 'pry'

STDOUT.sync = true
logger = Logger.new(STDOUT)

options = {}

OptionParser.new do |parser|
  parser.on("-t", "--token KEY", "Contentful management access token") do |v|
    options[:token] = v
  end
  parser.on("-s", "--space-id SPACEID", "Contentful space ID") do |v|
    options[:space_id] = v
  end
  parser.on("-p", "--type CONTENT_MODEL", "Contentful type to delete ID") do |v|
    options[:type] = v
  end
  parser.on("-c", "--command COMMAND", "Contentful command like publish, unpublish or destroy") do |v|
    options[:command] = v
  end
end.parse!

client = Contentful::Management::Client.new(options[:token], log_level: Logger::DEBUG)
space = client.spaces.find(options[:space_id])
content_type = space.content_types.find(options[:type])
entries = content_type.entries.all(limit: 100, order: 'sys.id')

loop do
  break if entries.count == 0

  # entries.each do |entry|
  Parallel.each(entries, in_threads: 5) do |entry|
    t = Benchmark.realtime do
      entry.send(options[:command])
    end

    logger.info({ duration: "#{t * 1000}ms", action: "entry.#{options[:command]}" }.to_json)
  end

  entries = entries.next_page
end
```

Seems to be some shared state across threads in the gem but haven't a chance to look. Using `in_processes` works though.

**Comment by dlitvakb** [comment]
Hey @Soliah,

I answered to this issue through our support channel.

Cheers

**Comment by Soliah** [comment]
Closing as we're using processes instead of threads to deal with this.
